MWPW-162832- Pass locale code to prelude
adobecom/unity pull request #155
Opened 2024-11-20 18:24 UTC by Ruchika4

- Pass locale code for locale mapping at prelude side

Resolves: [MWPW-162832](https://jira.corp.adobe.com/browse/MWPW-162832)

Test URLs:

Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=stage
After: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=locale-code

2024-11-20 20:13 UTC, sanjayms01 approved these changes

2024-11-21 06:11 UTC, aishwaryamathuria commented on unitylibs/scripts/utils.js
> +  return locale ? locale[0] : 'us';
Hi @Ruchika4 In place of splitting the url to find the locale and parsing through the object could we use the getConfig().locale? This property returned by config has the correct entry of the lcoale from the current url and can return the required property

2024-11-21 06:12 UTC, aishwaryamathuria requested changes
Hi @Ruchika4 In place of splitting the url to find the locale and parsing through the object could we use the getConfig().locale? This property returned by config has the correct entry of the locale from the current url and can return the required property

2024-11-21 06:31 UTC, Ruchika4 commented
> Hi @Ruchika4 In place of splitting the url to find the locale and parsing through the object could we use the getConfig().locale? This property returned by config has the correct entry of the locale from the current url and can return the required details.

Code has been updated. Please check.

2024-11-21 06:33 UTC, aishwaryamathuria approved these changes

2024-11-21 06:34 UTC, merged